// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is what the Settings menu needs about Kubereach itself.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ShowAbout opens the native About dialog.
 */
export function ShowAbout(): $CancellablePromise<void> {
    return $Call.ByID(1704954594);
}
