// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService holds what the About dialog shows about Kubereach itself, and its updates.
 * macOS shows the native dialog from its application menu; Windows and Linux draw it in the frontend from Info,
 * since the Windows message box has no buttons but OK.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AvailableUpdate is the release the last check found, for a window that loads after it was announced.
 */
export function AvailableUpdate(): $CancellablePromise<$models.Update | null> {
    return $Call.ByID(3393234826);
}

/**
 * CheckForUpdates asks GitHub for a newer release; nil when this one is the latest.
 */
export function CheckForUpdates(): $CancellablePromise<$models.Update | null> {
    return $Call.ByID(2705752831);
}

/**
 * DownloadUpdate downloads the release the last check found and verifies it against updateKey. Its progress
 * arrives as EventUpdateProgress.
 */
export function DownloadUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3266387825);
}

/**
 * Info is what the frontend's About dialog shows on Windows and Linux.
 */
export function Info(): $CancellablePromise<$models.AboutInfo> {
    return $Call.ByID(443785436);
}

/**
 * RestartToUpdate quits Kubereach, puts the downloaded release in its place and starts it.
 */
export function RestartToUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2761193519);
}

/**
 * Reveal selects the configuration file in the OS file manager, or opens its directory before the first save.
 */
export function Reveal(): $CancellablePromise<void> {
    return $Call.ByID(4117185365);
}
