// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService holds what the About dialog shows about Kubereach itself.
 * macOS shows the native dialog from its application menu; Windows and Linux draw it in the frontend from Info,
 * since the Windows message box has no buttons but OK.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Info is what the frontend's About dialog shows on Windows and Linux.
 */
export function Info(): $CancellablePromise<$models.AboutInfo> {
    return $Call.ByID(443785436);
}

/**
 * Reveal selects the configuration file in the OS file manager, or opens its directory before the first save.
 */
export function Reveal(): $CancellablePromise<void> {
    return $Call.ByID(4117185365);
}
