// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../service/models.js";

export function CheckReachability(clusterID: string): $CancellablePromise<string> {
    return $Call.ByID(3635985892, clusterID);
}

/**
 * Import opens the native file picker and imports every chosen kubeconfig.
 */
export function Import(): $CancellablePromise<service$0.Cluster[] | null> {
    return $Call.ByID(3379050484);
}

export function ListNamespaces(clusterID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1043487461, clusterID);
}

export function ListPods(clusterID: string): $CancellablePromise<service$0.KubePod[] | null> {
    return $Call.ByID(4065161353, clusterID);
}

export function ListServices(clusterID: string): $CancellablePromise<service$0.KubeService[] | null> {
    return $Call.ByID(2705149113, clusterID);
}

export function SetNamespaces(clusterID: string, namespaces: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2112128423, clusterID, namespaces);
}
