// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../service/models.js";

export function CheckReachability(clusterID: string): $CancellablePromise<string> {
    return $Call.ByID(273405860, clusterID);
}

export function Delete(clusterID: string): $CancellablePromise<void> {
    return $Call.ByID(2664650794, clusterID);
}

export function DescribePod(clusterID: string, $namespace: string, name: string): $CancellablePromise<service$0.PodDiagnosis> {
    return $Call.ByID(4197865875, clusterID, $namespace, name);
}

export function DescribeWorkload(clusterID: string, kind: service$0.WorkloadKind, $namespace: string, name: string): $CancellablePromise<service$0.WorkloadDiagnosis> {
    return $Call.ByID(3413420857, clusterID, kind, $namespace, name);
}

export function GetConfigMap(clusterID: string, $namespace: string, name: string): $CancellablePromise<service$0.KubeConfigObject> {
    return $Call.ByID(2292636801, clusterID, $namespace, name);
}

export function GetSecret(clusterID: string, $namespace: string, name: string): $CancellablePromise<service$0.KubeConfigObject> {
    return $Call.ByID(4277133519, clusterID, $namespace, name);
}

export function GetYAML(clusterID: string, kind: service$0.ObjectKind, $namespace: string, name: string, reveal: boolean): $CancellablePromise<string> {
    return $Call.ByID(2971271592, clusterID, kind, $namespace, name, reveal);
}

/**
 * Import opens the native file picker and imports every chosen kubeconfig.
 */
export function Import(): $CancellablePromise<service$0.Cluster[] | null> {
    return $Call.ByID(469537716);
}

export function ImportPaths(paths: string[] | null): $CancellablePromise<service$0.Cluster[] | null> {
    return $Call.ByID(3966526160, paths);
}

export function ListConfigMaps(clusterID: string): $CancellablePromise<service$0.KubeConfigObject[] | null> {
    return $Call.ByID(2756024224, clusterID);
}

export function ListNamespaces(clusterID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3507898021, clusterID);
}

export function ListPods(clusterID: string): $CancellablePromise<service$0.KubePod[] | null> {
    return $Call.ByID(1789994825, clusterID);
}

export function ListSecrets(clusterID: string): $CancellablePromise<service$0.KubeConfigObject[] | null> {
    return $Call.ByID(2427122018, clusterID);
}

export function ListServices(clusterID: string): $CancellablePromise<service$0.KubeService[] | null> {
    return $Call.ByID(2601677433, clusterID);
}

export function ListWorkloads(clusterID: string): $CancellablePromise<service$0.KubeWorkload[] | null> {
    return $Call.ByID(1696905001, clusterID);
}

export function SetNamespaces(clusterID: string, namespaces: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1583854951, clusterID, namespaces);
}
