// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../service/models.js";

/**
 * Export asks where to save and writes the configuration there; "" when cancelled.
 */
export function Export(): $CancellablePromise<string> {
    return $Call.ByID(2365364071);
}

export function Import(path: string, remap: { [_ in string]?: string } | null): $CancellablePromise<void> {
    return $Call.ByID(3622336776, path, remap);
}

/**
 * InspectImport opens the native file picker and previews the chosen file; nil when cancelled.
 */
export function InspectImport(): $CancellablePromise<service$0.ImportPreview | null> {
    return $Call.ByID(1786347306);
}

export function InspectPath(path: string): $CancellablePromise<service$0.ImportPreview> {
    return $Call.ByID(2971576276, path);
}

export function Load(): $CancellablePromise<service$0.Config> {
    return $Call.ByID(2848347053);
}

/**
 * PickPath opens the native file picker in the home directory and returns the chosen path, or "" when cancelled.
 */
export function PickPath(title: string): $CancellablePromise<string> {
    return $Call.ByID(3048582499, title);
}
