// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../service/models.js";

export function Start(clusterID: string): $CancellablePromise<service$0.EventStatus> {
    return $Call.ByID(671183301, clusterID);
}

export function Stop(streamID: string): $CancellablePromise<void> {
    return $Call.ByID(3460754199, streamID);
}
