// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../service/models.js";

export function Delete(forwardID: string): $CancellablePromise<void> {
    return $Call.ByID(2686325857, forwardID);
}

export function Save(pf: service$0.PortForward): $CancellablePromise<service$0.PortForward> {
    return $Call.ByID(3809231075, pf);
}

export function SetEnabled(forwardID: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(346894523, forwardID, enabled);
}

export function Statuses(): $CancellablePromise<service$0.ForwardStatus[] | null> {
    return $Call.ByID(1934843660);
}
