// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../service/models.js";

export function Start(src: service$0.LogSource): $CancellablePromise<service$0.LogStatus> {
    return $Call.ByID(2474166719, src);
}

export function Statuses(): $CancellablePromise<service$0.LogStatus[] | null> {
    return $Call.ByID(985526679);
}

export function Stop(streamID: string): $CancellablePromise<void> {
    return $Call.ByID(3577114949, streamID);
}
