// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AboutInfo is what the About dialog shows.
 */
export interface AboutInfo {
    "version": string;
    "configPath": string;
    "repoURL": string;
}
