// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AboutInfo is what the About dialog shows.
 */
export interface AboutInfo {
    "version": string;
    "configPath": string;
    "repoURL": string;

    /**
     * Updates is whether Check for updates is offered; dev builds have no updater.
     */
    "updates": boolean;
}

/**
 * Update is a newer release than the running one.
 */
export interface Update {
    "version": string;

    /**
     * Notes are the release's section of CHANGELOG.md, in Markdown.
     */
    "notes": string;

    /**
     * Size is the download's size in bytes.
     */
    "size": number;
}
