// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../service/models.js";

export function Resize(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(1854567153, sessionID, cols, rows);
}

export function Start(target: service$0.ShellTarget, cols: number, rows: number): $CancellablePromise<service$0.ShellStatus> {
    return $Call.ByID(3154817903, target, cols, rows);
}

export function Statuses(): $CancellablePromise<service$0.ShellStatus[] | null> {
    return $Call.ByID(2183046119);
}

export function Stop(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(4276100021, sessionID);
}

export function Write(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(281885068, sessionID, data);
}
