// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../service/models.js";

export function Resize(id: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(1012364935, id, cols, rows);
}

export function Start(clusterID: string, cols: number, rows: number): $CancellablePromise<service$0.TerminalStatus> {
    return $Call.ByID(104519205, clusterID, cols, rows);
}

export function Statuses(): $CancellablePromise<service$0.TerminalStatus[] | null> {
    return $Call.ByID(3850626373);
}

export function Stop(id: string): $CancellablePromise<void> {
    return $Call.ByID(2754621687, id);
}

export function Write(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(1347563122, id, data);
}
