// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as service$0 from "../../../../edereagzi/kubereach/internal/service/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "forward:state": service$0.ForwardStatus;
            "logs:lines": service$0.LogBatch;
            "logs:state": service$0.LogStatus;
            "route:hostkey": service$0.HostKeyPrompt;
            "route:state": service$0.RouteStatus;
        }
    }
}
