// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum AuthMethod {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthAgent = "agent",
    AuthKeyFile = "key",
    AuthPassword = "password",
};

export interface Cluster {
    "id": string;
    "name": string;
    "kubeconfig": string;
    "context": string;
    "route": string;
    "namespaces": string[] | null;
}

export interface Config {
    "version": number;
    "routes": Route[] | null;
    "clusters": Cluster[] | null;

    /**
     * Forwards are the Saved Forwards: Port Forward definitions kept across sessions.
     */
    "forwards": PortForward[] | null;
}

/**
 * ForwardStatus describes a bound forward: idle until the first inbound connection, connected while a pod
 * connection is up, error when the port could not be bound or the last dial failed.
 */
export interface ForwardStatus {
    "forward": PortForward;

    /**
     * Pod is the backing pod while a connection is up.
     */
    "pod": string;
    "state": State;
    "error"?: string;
}

export interface ForwardTarget {
    "kind": TargetKind;
    "namespace": string;
    "name": string;
}

export interface HostKeyPrompt {
    "routeId": string;
    "address": string;
    "keyType": string;
    "fingerprint": string;
}

/**
 * ImportPreview is what ImportConfig would add from a file: entries whose ID is not configured yet, how many
 * were skipped as duplicates, and every kubeconfig or key path in the new entries that does not exist locally.
 * A file without the export schema is a kubeconfig; only Path and Kubeconfig are set then.
 */
export interface ImportPreview {
    "path": string;
    "kubeconfig": boolean;
    "routes": Route[] | null;
    "clusters": Cluster[] | null;
    "forwards": PortForward[] | null;
    "duplicates": number;
    "missingPaths": string[] | null;
}

export interface KubePod {
    "namespace": string;
    "name": string;
    "containers": string[] | null;
    "ports": NamedPort[] | null;
}

export interface KubeService {
    "namespace": string;
    "name": string;
    "ports": NamedPort[] | null;
}

/**
 * KubeWorkload is a Deployment, StatefulSet or DaemonSet whose pods can be followed together.
 */
export interface KubeWorkload {
    "namespace": string;
    "name": string;
    "kind": LogSourceKind;
}

export interface LogBatch {
    "streamId": string;
    "lines": LogLine[] | null;
}

/**
 * LogLine carries the raw text; a line that is a JSON object also carries its top-level fields as strings.
 */
export interface LogLine {
    "pod": string;
    "container": string;
    "time": string;
    "text": string;
    "fields"?: { [_ in string]?: string } | null;
}

/**
 * LogSource is one pod, or a workload whose pods are followed together as they come and go.
 */
export interface LogSource {
    "clusterId": string;
    "namespace": string;
    "kind": LogSourceKind;
    "name": string;
}

export enum LogSourceKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LogSourcePod = "pod",
    LogSourceDeployment = "deployment",
    LogSourceStatefulSet = "statefulset",
    LogSourceDaemonSet = "daemonset",
};

export interface LogStatus {
    "id": string;
    "source": LogSource;

    /**
     * Pods are the pods currently followed; Containers is the union of their containers.
     */
    "pods": string[] | null;
    "containers": string[] | null;
    "state": State;
    "error"?: string;
}

/**
 * NamedPort is a service port or a container port.
 */
export interface NamedPort {
    "name": string;
    "port": number;
}

/**
 * PortForward binds a loopback port to one service or pod port; RemotePort is the service port for services.
 * A zero LocalPort is assigned by SaveForward; Enabled is whether the port is bound whenever Kubereach runs.
 */
export interface PortForward {
    "id": string;
    "clusterId": string;
    "target": ForwardTarget;
    "remotePort": number;
    "localPort": number;
    "enabled": boolean;
}

/**
 * Route is the ordered list of SSH Servers through which a Cluster is reached.
 */
export interface Route {
    "id": string;
    "name": string;
    "servers": SSHServer[] | null;
}

export interface RouteStatus {
    "routeId": string;
    "state": State;
    "error"?: string;
}

/**
 * SSHServer holds no secrets: key passphrases and passwords live in memory for the session only.
 */
export interface SSHServer {
    "host": string;
    "port": number;
    "user": string;
    "auth": AuthMethod;
    "keyFile": string;
}

export interface ShellOutput {
    "sessionId": string;
    "data": string | null;
}

export interface ShellStatus {
    "id": string;
    "target": ShellTarget;

    /**
     * Shell is the command currently being tried, then the one that started.
     */
    "shell": string;
    "state": State;
    "error"?: string;
}

/**
 * ShellTarget is the container an interactive shell is opened in; an empty Container means the pod's first one.
 */
export interface ShellTarget {
    "clusterId": string;
    "namespace": string;
    "pod": string;
    "container": string;
}

/**
 * State is the connection state machine shared by every connection-bearing entity.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateIdle = "idle",
    StateConnecting = "connecting",
    StateConnected = "connected",
    StateReconnecting = "reconnecting",
    StateStopped = "stopped",
    StateError = "error",
};

export enum TargetKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TargetService = "service",
    TargetPod = "pod",
};
