// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum AuthMethod {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthAgent = "agent",
    AuthKeyFile = "key",
    AuthPassword = "password",
};

export interface Cluster {
    "id": string;
    "name": string;
    "kubeconfig": string;
    "context": string;
    "route": string;
    "namespaces": string[] | null;
}

export interface Config {
    "version": number;
    "routes": Route[] | null;
    "clusters": Cluster[] | null;

    /**
     * Forwards are the Saved Forwards: Port Forward definitions kept across sessions.
     */
    "forwards": PortForward[] | null;
}

export interface ForwardStatus {
    "forward": PortForward;

    /**
     * Pod is the backing pod the forward resolved to.
     */
    "pod": string;
    "state": State;
    "error"?: string;
}

export interface ForwardTarget {
    "kind": TargetKind;
    "namespace": string;
    "name": string;
}

export interface HostKeyPrompt {
    "routeId": string;
    "address": string;
    "keyType": string;
    "fingerprint": string;
}

export interface KubePod {
    "namespace": string;
    "name": string;
    "ports": NamedPort[] | null;
}

export interface KubeService {
    "namespace": string;
    "name": string;
    "ports": NamedPort[] | null;
}

/**
 * NamedPort is a service port or a container port.
 */
export interface NamedPort {
    "name": string;
    "port": number;
}

/**
 * PortForward binds a loopback port to one service or pod port; RemotePort is the service port for services.
 */
export interface PortForward {
    "id": string;
    "clusterId": string;
    "target": ForwardTarget;
    "remotePort": number;
    "localPort": number;
}

/**
 * Route is the ordered list of SSH Servers through which a Cluster is reached.
 */
export interface Route {
    "id": string;
    "name": string;
    "servers": SSHServer[] | null;
}

export interface RouteStatus {
    "routeId": string;
    "state": State;
    "error"?: string;
}

/**
 * SSHServer holds no secrets: key passphrases and passwords live in memory for the session only.
 */
export interface SSHServer {
    "host": string;
    "port": number;
    "user": string;
    "auth": AuthMethod;
    "keyFile": string;
}

/**
 * State is the connection state machine shared by every connection-bearing entity.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateIdle = "idle",
    StateConnecting = "connecting",
    StateConnected = "connected",
    StateReconnecting = "reconnecting",
    StateStopped = "stopped",
    StateError = "error",
};

export enum TargetKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TargetService = "service",
    TargetPod = "pod",
};
