// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum AuthMethod {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthAgent = "agent",
    AuthKeyFile = "key",
    AuthPassword = "password",
};

export interface Cluster {
    "id": string;
    "name": string;
    "kubeconfig": string;
    "context": string;
    "route": string;
    "namespaces": string[] | null;
}

export interface Config {
    "version": number;
    "routes": Route[] | null;
    "clusters": Cluster[] | null;
}

export interface HostKeyPrompt {
    "routeId": string;
    "address": string;
    "keyType": string;
    "fingerprint": string;
}

export interface KubeService {
    "namespace": string;
    "name": string;
    "ports": ServicePort[] | null;
}

/**
 * Route is the ordered list of SSH Servers through which a Cluster is reached.
 */
export interface Route {
    "id": string;
    "name": string;
    "servers": SSHServer[] | null;
}

export interface RouteStatus {
    "routeId": string;
    "state": State;
    "error"?: string;
}

/**
 * SSHServer holds no secrets: key passphrases and passwords live in memory for the session only.
 */
export interface SSHServer {
    "host": string;
    "port": number;
    "user": string;
    "auth": AuthMethod;
    "keyFile": string;
}

export interface ServicePort {
    "name": string;
    "port": number;
}

/**
 * State is the connection state machine shared by every connection-bearing entity.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateIdle = "idle",
    StateConnecting = "connecting",
    StateConnected = "connected",
    StateReconnecting = "reconnecting",
    StateStopped = "stopped",
    StateError = "error",
};
