// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Progress is the payload of EventDownloadProgress.
 */
export interface Progress {
    "written": number;
    "total": number;

    /**
     * bytes/sec smoothed over the last ~1s
     */
    "rate": number;
    "provider"?: string;
}
